// <auto-generated />
using System;
using Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(tTSportDbContext))]
    partial class tTSportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Entities.DMBAIVIET", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("DMLOAIBAIVIETID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENBAI")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("DMLOAIBAIVIETID");

                    b.ToTable("DMBAIVIETs");
                });

            modelBuilder.Entity("Data.Entities.DMKHACHHANG", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENKHACH")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("DMKHACHHANGs");
                });

            modelBuilder.Entity("Data.Entities.DMLOAIBAIVIET", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENLOAI")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("DMLOAIBAIVIETs");
                });

            modelBuilder.Entity("Data.Entities.DMLOAIDICHVU", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENDICHVU")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("DMLOAIDICHVUs");
                });

            modelBuilder.Entity("Data.Entities.KETBAN", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KETBANs");
                });

            modelBuilder.Entity("Data.Entities.KHACHHANGDICHVU", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("DMKHACHHANGID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DMLOAIDICHVUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DMKHACHHANGID");

                    b.HasIndex("DMLOAIDICHVUID");

                    b.ToTable("KHACHHANGDICHVUs");
                });

            modelBuilder.Entity("Data.Entities.MESSAGE", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MESSAGE_BODY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBJECT")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("MESSAGEs");
                });

            modelBuilder.Entity("Data.Entities.MONTHETHAO", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("DISCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPORT_NAME")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("MONTHETHAOs");
                });

            modelBuilder.Entity("Data.Entities.NGUOIDUNG", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRSTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KETBANID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LASTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MESSAGEID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SEX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KETBANID");

                    b.HasIndex("MESSAGEID");

                    b.ToTable("NGUOIDUNGs");
                });

            modelBuilder.Entity("Data.Entities.TAOGIAI", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("DIADIEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("LOAIGIAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SOLUONGGIAI")
                        .HasColumnType("int");

                    b.Property<string>("TENGIAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("THOIGIAN")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("TAOGIAIs");
                });

            modelBuilder.Entity("Data.Entities.THETHAONGUOIDUNG", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATE_DAY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONTHETHAOID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NGUOIDUNGID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PRESTIGE_POINTS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MONTHETHAOID");

                    b.HasIndex("NGUOIDUNGID");

                    b.ToTable("THETHAONGUOIDUNGs");
                });

            modelBuilder.Entity("Data.Entities.DMBAIVIET", b =>
                {
                    b.HasOne("Data.Entities.DMLOAIBAIVIET", "DMLOAIBAIVIET")
                        .WithMany("DMBAIVIETs")
                        .HasForeignKey("DMLOAIBAIVIETID");

                    b.Navigation("DMLOAIBAIVIET");
                });

            modelBuilder.Entity("Data.Entities.KHACHHANGDICHVU", b =>
                {
                    b.HasOne("Data.Entities.DMKHACHHANG", "DMKHACHHANG")
                        .WithMany("KHACHHANGDICHVUs")
                        .HasForeignKey("DMKHACHHANGID");

                    b.HasOne("Data.Entities.DMLOAIDICHVU", "DMLOAIDICHVU")
                        .WithMany("KHACHHANGDICHVUs")
                        .HasForeignKey("DMLOAIDICHVUID");

                    b.Navigation("DMKHACHHANG");

                    b.Navigation("DMLOAIDICHVU");
                });

            modelBuilder.Entity("Data.Entities.NGUOIDUNG", b =>
                {
                    b.HasOne("Data.Entities.KETBAN", null)
                        .WithMany("NGUOIDUNGs")
                        .HasForeignKey("KETBANID");

                    b.HasOne("Data.Entities.MESSAGE", null)
                        .WithMany("NGUOIDUNGs")
                        .HasForeignKey("MESSAGEID");
                });

            modelBuilder.Entity("Data.Entities.THETHAONGUOIDUNG", b =>
                {
                    b.HasOne("Data.Entities.MONTHETHAO", "MONTHETHAO")
                        .WithMany()
                        .HasForeignKey("MONTHETHAOID");

                    b.HasOne("Data.Entities.NGUOIDUNG", "NGUOIDUNG")
                        .WithMany("THETHAONGUOIDUNGs")
                        .HasForeignKey("NGUOIDUNGID");

                    b.Navigation("MONTHETHAO");

                    b.Navigation("NGUOIDUNG");
                });

            modelBuilder.Entity("Data.Entities.DMKHACHHANG", b =>
                {
                    b.Navigation("KHACHHANGDICHVUs");
                });

            modelBuilder.Entity("Data.Entities.DMLOAIBAIVIET", b =>
                {
                    b.Navigation("DMBAIVIETs");
                });

            modelBuilder.Entity("Data.Entities.DMLOAIDICHVU", b =>
                {
                    b.Navigation("KHACHHANGDICHVUs");
                });

            modelBuilder.Entity("Data.Entities.KETBAN", b =>
                {
                    b.Navigation("NGUOIDUNGs");
                });

            modelBuilder.Entity("Data.Entities.MESSAGE", b =>
                {
                    b.Navigation("NGUOIDUNGs");
                });

            modelBuilder.Entity("Data.Entities.NGUOIDUNG", b =>
                {
                    b.Navigation("THETHAONGUOIDUNGs");
                });
#pragma warning restore 612, 618
        }
    }
}
